site_name: RNCP
nav:
  - RNCP:
    - Plan: rncp/index.md
    - RNCP: rncp/rncp.md
    - Projets web:
      - piscine: rncp/piscine_web.md
      - bottle: rncp/bottle.md
      - flask: rncp/flask.md
      - django: rncp/django.md
    - Projets mobile:
      - piscine: rncp/piscine_mobile.md
      - flutter: rncp/flutter.md
    - KFS:
      - ft_linux: rncp/ft_linux.md
      - little_penguin: rncp/little_penguin.md
      - kf1: rncp/kfs1.md
      - kf2: rncp/kfs2.md
    - Stages:
      - pybot: rncp/pybot.md
  - MEEF:
      - programme: meef/index.md
      - enseigner: meef/teach.md
      - pedagogie: meef/pedago.md
      - alter: meef/alter.md
  - NSI:
    - programme: nsi/index.md
    - college (cycle 4): nsi/college.md
    - scratch: nsi/scratch.md
    - html & css: nsi/htmlcss.md
    - python: nsi/python.md
    - snt: nsi/snt.md
    - nsi 1ere - cours: nsi/nsi_1.md
    - nsi Term - cours: nsi/nsi_t.md
    - bac - programme: nsi/bac_p.md
    - bac - exams: nsi/bac_e.md
    - capes - programme: nsi/capes_p.md
    - capes - exams: nsi/capes_e.md
    - liste projets: nsi/projets.md
  - YUPICOS: yupicos/index.md
  

theme: 
  icon:
    logo: material/robot-love-outline
    favicon: images/favicon.png
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs
  #   - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences