site_name: RNCP
nav:
  - RNCP:
    - Programme: index.md
    - Projets web:
      - python: rncp/python.md
      - bottle: rncp/bottle.md
      - flask: rncp/flask.md
      - django: rncp/django.md
      - js/html/css: rncp/web.md
      - camagru: rncp/camagru.md
      - matcha: rncp/matcha.md
    - Projets mobile:
      - flutter: rncp/flutter.md
      - ft_hangouts: rncp/ft_hangouts.md
      - swifty-companion: rncp/swifty.md
    - Projets graphique:
      - vala: rncp/vala.md
      - opengl: rncp/opengl.md
      - scop: rncp/scop.md
      - humangl: rncp/humangl.md
      # - bomberman: rncp/bomberman.md
    - Stages:
      - École 42: rncp/stage42.md
  - MEEF:
      - programme: meef/index.md
      - enseigner: meef/teach.md
      - pedagogie: meef/pedago.md
      # - alter: meef/alter.md
  - NSI:
    - programme: nsi/index.md
    - college (cycle 4): nsi/college.md
    - scratch: nsi/scratch.md
    - html, css et js: nsi/web.md
    - python: nsi/python.md
    - snt: nsi/snt.md
    - nsi 1ere - cours: nsi/nsi_1.md
    - nsi Term - cours: nsi/nsi_t.md
    - bac - programme: nsi/bac_p.md
    - bac - exams: nsi/bac_e.md
    - capes - programme: nsi/capes_p.md
    - capes - exams: nsi/capes_e.md
    # - liste projets: nsi/projets.md
  - YUPICOS: 
    - projet: yupicos/index.md
    - pygame: yupicos/pygame.md

theme: 
  icon:
    logo: material/penguin
    favicon: images/favicon.png
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences