site_name: RNCP
nav:
  - RNCP:
    - Plan: index.md
    - RNCP: rncp.md
    - Projets unix:
      - libft: libft.md
      - ft_ls: ft_ls.md
      - libasm: libasm.md
      - taskmaster: taskmaster.md
    - Projets sécurité:
      - modules: secu.md
    - Projets réseaux:
      - ft_ping: ft_ping.md
  - KFS:
    - intro: kfs_intro.md
    - kf1: kfs1.md
    - kf2: kfs2.md
  - NSI:
    - college (cycle 4): college.md
    - snt: snt.md
    - nsi 1ere - cours: nsi_1.md
    - nsi Term - cours: nsi_t.md
    - bac - programme: bac_p.md
    - bac - exams: bac_e.md
    - capes - programme: capes_p.md
    - capes - exams: capes_e.md

theme: 
  icon:
    logo: material/robot-love-outline
    favicon: images/favicon.png
  name: material 
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Passer au mode clair
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    # - navigation.tabs
  #   - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences